version: "3.9"
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npm run dev